window.HIGH_STYLE_BRANDS = {
  "high-style": {
    businessName: "High Style Creative",
    displayName: "High Style Creative",
    eyebrow: "Digital business card",
    personName: "",
    role: "Hospitality Photography & Content",
    tagline: "Capturing Culinary Creativity",
    logo: "",
    initials: "HS",
    theme: {
      background: "#050505",
      surface: "#101010",
      text: "#ffffff",
      muted: "#9a9a9a",
      accent: "#ffffff",
      accentText: "#050505",
      border: "#262626"
    },
    phone: "+447555481441",
    phoneDisplay: "07555 481441",
    whatsapp: "+447555481441",
    email: "",
    website: "",
    instagram: "https://www.instagram.com/high_style_creative/",
    instagramLabel: "@high_style_creative",
    linkedin: "",
    tiktok: "",
    bookingUrl: "../booking.html",
    bookingLabel: "Book a Shoot",
    appleWalletUrl: "",
    googleWalletUrl: "",
    services: ["Food Photography", "Drink Photography", "Hospitality Content", "Social Content"],
    review: "",
    location: "UK",
    gallery: [],
    footer: "Powered by High Style Cards"
  },

  "starter": {
    businessName: "Your Brand",
    displayName: "Your Brand",
    eyebrow: "Digital business card",
    personName: "Your Name",
    role: "Your role or service",
    tagline: "A short line that explains what makes the brand different.",
    logo: "",
    initials: "YB",
    theme: {
      background: "#f3efe7",
      surface: "#ffffff",
      text: "#181818",
      muted: "#6b675f",
      accent: "#181818",
      accentText: "#ffffff",
      border: "#ded8cc"
    },
    phone: "",
    phoneDisplay: "",
    whatsapp: "",
    email: "",
    website: "",
    instagram: "",
    instagramLabel: "",
    linkedin: "",
    tiktok: "",
    bookingUrl: "",
    bookingLabel: "Make an Enquiry",
    appleWalletUrl: "",
    googleWalletUrl: "",
    services: ["Service One", "Service Two", "Service Three"],
    review: "Add a customer review or testimonial here.",
    location: "Your location / areas covered",
    gallery: [],
    footer: "Powered by High Style Cards"
  }
};
