window.HIGH_STYLE_BRANDS = {
  "high-style": {
    businessName: "High Style Creative",
    displayName: "High Style Creative",
    eyebrow: "Digital business card",
    personName: "",
    role: "Hospitality Photography & Content",
    tagline: "Capturing Culinary Creativity",
    logo: "",
    initials: "HS",
    theme: {
      background: "#050505",
      surface: "#101010",
      text: "#ffffff",
      muted: "#9a9a9a",
      accent: "#ffffff",
      accentText: "#050505",
      border: "#262626"
    },
    phone: "+447555481441",
    phoneDisplay: "07555 481441",
    whatsapp: "+447555481441",
    email: "",
    website: "",
    instagram: "https://www.instagram.com/high_style_creative/",
    instagramLabel: "@high_style_creative",
    linkedin: "",
    tiktok: "",
    bookingUrl: "../booking.html",
    bookingLabel: "Book a Shoot",
    appleWalletUrl: "",
    googleWalletUrl: "",
    services: ["Food Photography", "Drink Photography", "Hospitality Content", "Social Content"],
    review: "",
    location: "UK",
    gallery: [],
    animations: {
      entrance: "reveal",
      buttons: "wave",
      accent: "halo"
    },
    footer: "Powered by High Style Cards"
  },

  "cancello": {
    businessName: "Cancello Bar & Restaurant",
    displayName: "Cancello",
    eyebrow: "Italian Bar & Restaurant",
    personName: "",
    role: "Northern Italian Cuisine",
    tagline: "Authentic Italian food, great wine and warm hospitality.",
    logo: "https://static.wixstatic.com/media/8e77a0_14d664a9ae2245329222d55691ced44d~mv2.jpg/v1/fill/w_397,h_186,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/cancello-final-logo.jpg",
    initials: "C",
    theme: {
      background: "#eee8dc",
      surface: "#11100e",
      text: "#f8f3e8",
      muted: "#b8ae9d",
      accent: "#c6a56a",
      accentText: "#17130d",
      border: "#39342b",
      headingFont: "\"Cormorant Garamond\", Georgia, serif",
      bodyFont: "Manrope, Arial, sans-serif",
      fontLabel: "Italian Luxury",
      fontChoice: "cormorant"
    },
    phone: "+441925291555",
    phoneDisplay: "01925 291555",
    whatsapp: "",
    email: "info@cancellorestaurant.com",
    website: "https://www.cancellorestaurant.com/",
    instagram: "https://www.instagram.com/arieterestaurant/",
    instagramLabel: "@arieterestaurant",
    linkedin: "",
    tiktok: "",
    bookingUrl: "https://www.cancellorestaurant.com/reservations",
    bookingLabel: "Book a Table",
    menuUrl: "https://www.cancellorestaurant.com/menu",
    menuLabel: "View Our Menus",
    tripadvisorUrl: "https://www.tripadvisor.co.uk/Restaurant_Review-g528810-d841168-Reviews-Cancello_Bar_And_Restaurant-Newton_Le_Willows_Merseyside_England.html",
    services: ["Italian Dining", "Wine & Cocktails", "Private Hire", "Celebrations"],
    review: "",
    location: "136 High Street · Newton-le-Willows · WA12 9SG",
    gallery: [],
    actions: [
      {type:"booking",label:"Book a Table",primary:false},
      {type:"instagram",label:"Instagram",primary:false},
      {type:"phone",label:"Call Cancello",primary:false},
      {type:"email",label:"Email",primary:false},
      {type:"website",label:"Website",primary:false}
    ],
    buttonSettings: {managed:true,hidden:[],saveContact:false},
    saveContactEnabled: false,
    animations: {
      entrance: "reveal",
      buttons: "wave",
      accent: "halo"
    },
    footer: "Powered by High Style Cards"
  },

  "starter": {
    businessName: "Your Brand",
    displayName: "Your Brand",
    eyebrow: "Digital business card",
    personName: "Your Name",
    role: "Your role or service",
    tagline: "A short line that explains what makes the brand different.",
    logo: "",
    initials: "YB",
    theme: {
      background: "#f3efe7",
      surface: "#ffffff",
      text: "#181818",
      muted: "#6b675f",
      accent: "#181818",
      accentText: "#ffffff",
      border: "#ded8cc"
    },
    phone: "",
    phoneDisplay: "",
    whatsapp: "",
    email: "",
    website: "",
    instagram: "",
    instagramLabel: "",
    linkedin: "",
    tiktok: "",
    bookingUrl: "",
    bookingLabel: "Make an Enquiry",
    appleWalletUrl: "",
    googleWalletUrl: "",
    services: ["Service One", "Service Two", "Service Three"],
    review: "Add a customer review or testimonial here.",
    location: "Your location / areas covered",
    gallery: [],
    footer: "Powered by High Style Cards"
  }
};
